# Generated by Django 3.1.1 on 2020-10-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_new_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='bhuvan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('ismarried', models.BooleanField(default=False)),
            ],
        ),
    ]
