# Generated by Django 3.1.1 on 2020-10-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201011_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_test',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
