# Generated by Django 3.1.1 on 2020-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20201022_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypted_data',
            name='sendby',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='encrypted_data',
            name='sendto',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
