# Generated by Django 3.1.1 on 2020-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_bhuvan'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrmlimg', models.ImageField(upload_to='pics')),
                ('msg', models.TextField()),
                ('sensitivity', models.TextField()),
                ('secret_key', models.TextField()),
                ('encryimg', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='bhuvan',
        ),
    ]
