# Generated by Django 3.1.1 on 2020-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20201011_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrmlimg', models.ImageField(upload_to='pics')),
                ('msg', models.TextField()),
                ('sensitivity', models.TextField()),
                ('secret_key', models.TextField()),
                ('encryimg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
