# Generated by Django 3.1.1 on 2020-10-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20201022_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_table',
            new_name='encrypted_data',
        ),
    ]
