# Generated by Django 3.1.1 on 2020-11-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20201024_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transactions',
        ),
    ]
